export const skills = [
    'Object-Oriented Programming (OOP)',
    'JavaScript',
    'jQuery',
    'Node.js',
    'Testing with Jest',
    'Git',
    'Bash',
    'Developer Tools',
    'Template Engines',
    'React.js',
    'Next.js',
    'Material UI',
    'Bootstrap',
    'React Testing Library',
    'React Hooks',
    'styled-components',
    'Responsive Design with Flexbox & Grid',
    'CSS Preprocessors',
    'Sass & Less',
    'Amazon Web Services',
    'Amazon S3',
    'Web Accessibility Initiative (WAI-ARIA)',
];